# Generated by Django 5.2.6 on 2025-10-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_livraison',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
