# Generated by Django 5.2.6 on 2025-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('paydunya', 'PayDunya (Wave, Orange, Carte)'), ('livraison', 'Paiement à la livraison')], default='paydunya', max_length=50),
        ),
    ]
