# Generated by Django 5.2.6 on 2025-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('validée', 'Validée et en préparation'), ('annulee', 'Annulée'), ('livree', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
