# Generated by Django 5.2.6 on 2025-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
