# Generated by Django 5.2.6 on 2025-09-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Client', 'Client')], default='Client', max_length=20),
        ),
    ]
