# Generated by Django 5.2.6 on 2025-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Client', 'Client'), ('Livreur', 'Livreur')], default='Client', max_length=20),
        ),
    ]
