# Generated by Django 5.2.6 on 2025-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_saison_pluies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_saison_seche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
