# Generated by Django 5.2.6 on 2025-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_produit_prix_produit_prix_saison_pluies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
